[versions]
# plugins
intelliJPlatform = "2.5.0"
kotlin = "2.1.20"

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }